/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CasaLubetkin.Frontend;

/**
 *
 * @author santiago
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Casa Lubetkin");
        panelOptions.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelNotifications = new javax.swing.JPanel();
        labelNotifications = new javax.swing.JLabel();
        panelOptions = new javax.swing.JPanel();
        buttonModifyI = new javax.swing.JButton();
        buttonModifyE = new javax.swing.JButton();
        buttonModifyS = new javax.swing.JButton();
        panelButtons = new javax.swing.JPanel();
        buttonRegI = new javax.swing.JButton();
        buttonRegE = new javax.swing.JButton();
        buttonReaC = new javax.swing.JButton();
        optionButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("MainPage"); // NOI18N
        setResizable(false);

        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelNotifications.setBackground(new java.awt.Color(255, 255, 255));
        panelNotifications.setBorder(new javax.swing.border.MatteBorder(null));

        labelNotifications.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelNotifications.setText("Notificaciones");

        javax.swing.GroupLayout panelNotificationsLayout = new javax.swing.GroupLayout(panelNotifications);
        panelNotifications.setLayout(panelNotificationsLayout);
        panelNotificationsLayout.setHorizontalGroup(
            panelNotificationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNotificationsLayout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(labelNotifications)
                .addGap(74, 74, 74))
        );
        panelNotificationsLayout.setVerticalGroup(
            panelNotificationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNotificationsLayout.createSequentialGroup()
                .addComponent(labelNotifications)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelPrincipal.add(panelNotifications, new org.netbeans.lib.awtextra.AbsoluteConstraints(826, 11, -1, 624));

        panelOptions.setBackground(new java.awt.Color(255, 255, 204));
        panelOptions.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 102)));

        buttonModifyI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconExit.png"))); // NOI18N
        buttonModifyI.setBorderPainted(false);
        buttonModifyI.setMaximumSize(new java.awt.Dimension(55, 55));
        buttonModifyI.setMinimumSize(new java.awt.Dimension(55, 55));
        buttonModifyI.setPreferredSize(new java.awt.Dimension(55, 55));
        buttonModifyI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModifyIActionPerformed(evt);
            }
        });

        buttonModifyE.setText("Modificar un ingreso");
        buttonModifyE.setMaximumSize(new java.awt.Dimension(55, 55));
        buttonModifyE.setMinimumSize(new java.awt.Dimension(55, 55));
        buttonModifyE.setPreferredSize(new java.awt.Dimension(55, 55));
        buttonModifyE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModifyEActionPerformed(evt);
            }
        });

        buttonModifyS.setText("Modificar un egreso");
        buttonModifyS.setMaximumSize(new java.awt.Dimension(55, 55));
        buttonModifyS.setMinimumSize(new java.awt.Dimension(55, 55));
        buttonModifyS.setPreferredSize(new java.awt.Dimension(55, 55));

        javax.swing.GroupLayout panelOptionsLayout = new javax.swing.GroupLayout(panelOptions);
        panelOptions.setLayout(panelOptionsLayout);
        panelOptionsLayout.setHorizontalGroup(
            panelOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonModifyE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(buttonModifyS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(buttonModifyI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelOptionsLayout.setVerticalGroup(
            panelOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOptionsLayout.createSequentialGroup()
                .addComponent(buttonModifyE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonModifyS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonModifyI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelPrincipal.add(panelOptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 72, -1, -1));

        buttonRegI.setText("Registrar ingreso");
        buttonRegI.setBorder(null);
        buttonRegI.setName(""); // NOI18N
        buttonRegI.setPreferredSize(new java.awt.Dimension(75, 25));
        buttonRegI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegIActionPerformed(evt);
            }
        });

        buttonRegE.setText("Registrar egreso");
        buttonRegE.setPreferredSize(new java.awt.Dimension(75, 25));
        buttonRegE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegEActionPerformed(evt);
            }
        });

        buttonReaC.setText("Realizar consultas");
        buttonReaC.setPreferredSize(new java.awt.Dimension(75, 25));
        buttonReaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReaCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelButtonsLayout = new javax.swing.GroupLayout(panelButtons);
        panelButtons.setLayout(panelButtonsLayout);
        panelButtonsLayout.setHorizontalGroup(
            panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonsLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonReaC, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addComponent(buttonRegE, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addComponent(buttonRegI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        panelButtonsLayout.setVerticalGroup(
            panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonsLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(buttonRegI, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(buttonRegE, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(buttonReaC, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
        );

        panelPrincipal.add(panelButtons, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 11, -1, -1));

        optionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconOption.png"))); // NOI18N
        optionButton.setMaximumSize(new java.awt.Dimension(55, 55));
        optionButton.setMinimumSize(new java.awt.Dimension(55, 55));
        optionButton.setPreferredSize(new java.awt.Dimension(55, 55));
        optionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionButtonActionPerformed(evt);
            }
        });
        panelPrincipal.add(optionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRegIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegIActionPerformed
        RegistrationIncome r = new RegistrationIncome();
        this.setVisible(false);
        r.setVisible(true);
    }//GEN-LAST:event_buttonRegIActionPerformed

    private void buttonRegEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegEActionPerformed
        RegistrationEgress r = new RegistrationEgress();
        this.setVisible(false);
        r.setVisible(true);
    }//GEN-LAST:event_buttonRegEActionPerformed

    private void buttonModifyIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModifyIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonModifyIActionPerformed

    private void buttonModifyEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModifyEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonModifyEActionPerformed

    private void optionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionButtonActionPerformed
        panelOptions.setVisible(false);
        if (optionButton.isSelected()) {
            panelOptions.setVisible(true);  
        }
    }//GEN-LAST:event_optionButtonActionPerformed

    private void buttonReaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReaCActionPerformed
        QueryPage qp = new QueryPage();
        this.setVisible(false);
        qp.setVisible(true);
    }//GEN-LAST:event_buttonReaCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonModifyE;
    private javax.swing.JButton buttonModifyI;
    private javax.swing.JButton buttonModifyS;
    private javax.swing.JButton buttonReaC;
    private javax.swing.JButton buttonRegE;
    private javax.swing.JButton buttonRegI;
    private javax.swing.JLabel labelNotifications;
    private javax.swing.JToggleButton optionButton;
    private javax.swing.JPanel panelButtons;
    private javax.swing.JPanel panelNotifications;
    private javax.swing.JPanel panelOptions;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
